data:
  root_dir: /root/EG1800
  image_dir: Images
  label_dir: Labels
  train_split: eg1800_train.txt
  test_split: eg1800_test.txt
  input_size: [224, 224]
  batch_size: 64

model:
  backbone_type: resnet50
  num_classes: 1

training:
  epochs: 50
  val_epochs: 5
  lr: 0.001

infer:
  image_dir: TO_BE_SET

work_dir: log

device: cuda
