data:
  data_type: matting_human
  root_dir: /kaggle/input/aisegmentcom-matting-human-datasets/
  image_dir: clip_img
  label_dir: matting
  # train_split: eg1800_train.txt
  # test_split: eg1800_test.txt
  train_range: [0, 0.5]
  test_range: [0.5, 0.6]
  input_size: [224, 224]
  batch_size: 16

model:
  backbone_type: resnet50
  num_classes: 1

training:
  epochs: 30
  val_epochs: 5
  lr: 0.001

infer:
  image_dir: TO_BE_SET

work_dir: log

device: cuda
